/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3a8c7f0c-8c4a-4a58-acc1-fe6e9a565a5c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NVG1yLxtp",
    "aws_user_pools_web_client_id": "cj98327a8dr9abh3q8al1f01f",
    "oauth": {}
};


export default awsmobile;
